GET http://localhost:5500/api/product/

// Add an id to find a specific product

###

GET http://localhost:5500/api/product

// Get all products should be adminSecure

###

//Add new product
POST http://localhost:5500/api/product
Content-Type: application/json

{
  "name": "Meiner @ the gym",
  "description": "Meiner in the gym. Some say it was leg-day but who knows?",
  "price": 19,
  "stock": 10
}

###

GET http://localhost:5500/api/product

// Each category needs an ID to find a specific product from that category




PUT http://localhost:5500/api/order/
// add an id to update a specific order
Content-Type: application/json

{
  "stock": "5",
}

###

