GET http://localhost:5500/api/product/

// Add an id to find a specific product

###

GET http://localhost:5500/api/product

// Get all products should be adminSecure

###

GET http://localhost:5500/api/product

// Each category needs an ID to find a specific product from that category

###

POST http://localhost:5500/api/product
Content-Type: application/json

{
  "name": "Zlatan",
  "description": "This is a product",
  "image": "This is an image",
  "price": 10
}

###


PUT http://localhost:5500/api/order/
// add an id to update a specific order
Content-Type: application/json

{
  "stock": 5,
}

###

