GET http://localhost:5500/api/product/628b91e600903aa79365db67

// Add an id to find a specific product

###

GET http://localhost:5500/api/product

// Get all products should be adminSecure

###

///////// CATEGORIES
//SELFIES: 62875632b98b2d20ac23d547
//THINGS: 62875635b98b2d20ac23d549
//LOGOS: 62875639b98b2d20ac23d54b

###

//Add new product
POST http://localhost:5500/api/product
Content-Type: application/json

{
  "categories": "62875632b98b2d20ac23d547",
  "name": "BakkumNFT #7",
  "description": "Bakkum with a black eye. Legend says it was given to him by the bouncer at Excet who got jealous of Felix one night.",
  "price": 16,
  "stock": 10,
  "imageId": "628b90e800903aa79365db65"
}

###

GET http://localhost:5500/api/product

// Each category needs an ID to find a specific product from that category




PUT http://localhost:5500/api/order/
// add an id to update a specific order
Content-Type: application/json

{
  "stock": "5",
}

###

