### Get all delivery options

GET http://localhost:5500/api/deliveryOptions


### Get a single delivery option

GET http://localhost:5500/api/deliveryOptions/:id

###

POST http://localhost:5500/api/deliveryOptions

Content-Type: application/json

{
    "title": "Postnord home delivery",
    "price": 4,
    "description": "Home delivery next day. Delivered between 10AM-9PM",
    "expectedDeliveryTime": 2,
    "imageId": "629094de2bfc3f38eacd67c7",
}


