GET http://localhost:5500/api/order

###

POST http://localhost:5500/api/order
Content-Type: application/json

{
  "customer":"628cebb2f92894356baa4597",
  "products": "628c9d841c4eb76ecbc12f8b",
  "deliveryAddress": {
    "firstName": "John",
    "lastName": "Doe",
    "street": "Teststraße",
    "number": "1",
    "zipcode": "12345",
    "city": "Teststadt"
  },
  "paymentMethod": "Swish",
  "deliveryMethod": "Postnord",
  "isSent": "true",
  "createdAt": "2018-01-01T00:00:00.000Z",
  "updatedAt": "2018-01-02T00:00:00.000Z"
}

###

PUT http://localhost:5500/api/order/6283515af3f6ab16ccf62710
Content-Type: application/json

{
  
}

###

DELETE http://localhost:5500/api/order/1234