POST http://localhost:5500/api/media
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="RamonadeNoccoNFT.png"
Content-Type: image/png

< ./RamonadeNoccoNFT.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://localhost:5500/api/media/628c9a1e1c4eb76ecbc12f75


###

DELETE http://localhost:5500/api/media/628b68c741452817c64950c2